import { db, assetEvents } from '@rcos/db';
import type { NewAssetEvent } from '@rcos/db';

export type EmitInput = {
  companyId: string;
  assetId: string;
  eventType: NewAssetEvent['eventType'];
  actorUserId?: string | null;
  source?: string;
  before?: Record<string, unknown> | undefined;
  after?: Record<string, unknown> | undefined;
  delta?: Record<string, unknown> | undefined;
  note?: string;
  context?: Record<string, unknown>;
};

/**
 * Append an immutable event to the asset log. Never throws to the caller if
 * the DB write fails — logs and continues; asset mutations must not be blocked
 * by observability failures.
 *
 * Downstream (Phase 8) an event-stream shipper will subscribe to this table
 * and forward to the AI training pipeline.
 */
export async function emitAssetEvent(input: EmitInput): Promise<void> {
  try {
    await db.insert(assetEvents).values({
      companyId: input.companyId,
      assetId: input.assetId,
      eventType: input.eventType,
      actorUserId: input.actorUserId ?? null,
      source: input.source ?? 'web',
      payload: {
        ...(input.before !== undefined ? { before: input.before } : {}),
        ...(input.after !== undefined ? { after: input.after } : {}),
        ...(input.delta !== undefined ? { delta: input.delta } : {}),
        ...(input.note ? { note: input.note } : {}),
      },
      context: input.context ?? {},
    });
  } catch (err) {
    // Deliberately non-fatal
    // eslint-disable-next-line no-console
    console.error('emitAssetEvent failed', err);
  }
}

/** Shallow diff producing { field: [before, after] } for jsonb-friendly delta. */
export function shallowDiff<T extends Record<string, unknown>>(
  before: T,
  after: T,
): Record<string, [unknown, unknown]> {
  const out: Record<string, [unknown, unknown]> = {};
  const keys = new Set([...Object.keys(before), ...Object.keys(after)]);
  for (const k of keys) {
    if (before[k] !== after[k]) out[k] = [before[k], after[k]];
  }
  return out;
}

/**
 * Compose an asset's AI summary + machine-readable feature blob. Kept simple
 * for Phase 2 — richer summaries get generated by the Phase 8 pipeline.
 */
export function composeAssetAiFields(input: {
  nameEn: string;
  manufacturer?: string | null;
  model?: string | null;
  kind: string;
  status: string;
  criticality: string;
  categoryPath?: string;
  areaKind?: string | null;
  branchCity?: string | null;
  spec?: Record<string, unknown>;
}): { aiSummary: string; aiMetadata: Record<string, unknown>; searchText: string } {
  const parts = [
    input.nameEn,
    input.manufacturer,
    input.model,
    input.categoryPath,
    input.kind,
    input.areaKind,
    input.branchCity,
    input.status,
  ]
    .filter(Boolean)
    .join(' · ');

  const aiMetadata = {
    kind: input.kind,
    status: input.status,
    criticality: input.criticality,
    categoryPath: input.categoryPath ?? null,
    areaKind: input.areaKind ?? null,
    hasSpec: !!input.spec && Object.keys(input.spec).length > 0,
    specKeys: input.spec ? Object.keys(input.spec) : [],
  };

  const searchText = [
    input.nameEn,
    input.manufacturer,
    input.model,
    input.categoryPath,
    input.kind,
    input.status,
    input.areaKind,
    input.branchCity,
    input.spec ? JSON.stringify(input.spec) : '',
  ]
    .filter(Boolean)
    .join(' ')
    .toLowerCase();

  return { aiSummary: parts, aiMetadata, searchText };
}
